Why NumPy is essential

Python lists can store numerical data, but NumPy provides:

Fast numerical computation
Multidimensional arrays
Vectorized operations
Broadcasting
Statistical calculations
Matrix operations
Random-number generation
Foundations for Pandas, scikit-learn, PyTorch, and many ML libraries

1.Python list versus NumPy array

In [3]:
import numpy as np


python_list = [10, 20, 30, 40]

numpy_array = np.array([10, 20, 30, 40])

print("Python list:")
print(python_list)

print("\nNumPy array:")
print(numpy_array)

print("\nTypes:")
print(type(python_list))
print(type(numpy_array))

Python list:
[10, 20, 30, 40]

NumPy array:
[10 20 30 40]

Types:
<class 'list'>
<class 'numpy.ndarray'>


2. Array Creation

In [2]:
import numpy as np

student_marks = np.array([80, 75, 90, 85])

print("Student Marks:")
print(student_marks)

sales = np.array([
    [100, 120, 140],
    [200, 220, 240]
])

print("\nSales Data:")
print(sales)

Student Marks:
[80 75 90 85]

Sales Data:
[[100 120 140]
 [200 220 240]]


3. Array Properties

In [ ]:
#sales comes from cell 2
print("Shape:", sales.shape)
print("Dimensions:", sales.ndim)
print("Size:", sales.size)
print("Datatype:", sales.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Datatype: int64


4. Datatypes

In [5]:
prices = np.array([10.5, 20.5, 30.5])

print(prices)
print(prices.dtype)

[10.5 20.5 30.5]
float64


5. Indexing

In [6]:
marks = np.array([70,80,90,100])

print(marks[0])
print(marks[-1])

70
100


6. Slicing

In [7]:
marks = np.array([70,80,90,100,110])

print(marks[1:4])

[ 80  90 100]


7. Multi-Dimensional Indexing

In [8]:
scores = np.array([
    [80,85,90],
    [75,78,82]
])

print(scores[1,2])

82


8. Array Arithmetic

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


9. Broadcasting

In [10]:
salary = np.array([
    [30000,32000],
    [35000,36000]
])

bonus = 5000

new_salary = salary + bonus

print(new_salary)

[[35000 37000]
 [40000 41000]]


10. Aggregation Functions

In [14]:
marks = np.array([80,75,90,95])

print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Standard Deviation:", np.std(marks))

Sum: 340
Mean: 85.0
Minimum: 75
Maximum: 95
Standard Deviation: 7.905694150420948


11. Axis Operations

In [ ]:
sales = np.array([
    [100,200,300],
    [400,500,600]
])

print("Column Sum:")
print(np.sum(sales, axis=0))  #vertical

print("Row Sum:")
print(np.sum(sales, axis=1))  #horizontal

Column Sum:
[500 700 900]
Row Sum:
[ 600 1500]


12. Reshape

In [16]:
numbers = np.array([1,2,3,4,5,6])

reshaped = numbers.reshape(2,3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


13. Flatten

In [17]:
matrix = np.array([
    [1,2],
    [3,4]
])

print(matrix.flatten())

[1 2 3 4]


14. Transpose

In [18]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


15. Random Numbers

In [20]:
np.random.seed(42)

random_numbers = np.random.randint(
    1,
    1000,
    100
)

print(random_numbers)

[103 436 861 271 107  72 701  21 615 122 467 215 331 459  88 373 100 872
 664 131 662 309 770 344 492 414 806 386 192 956 277 161 460 314  22 253
 748 857 561 475  59 511 682 476 700 976 783 190 958 687 958 563 876 567
 244 832 505 131 485 819 647  21 841 167 274 388 601 316  14 242 777 346
 565 898 340  92 367 956 455 428 509 776 943  35 206  81 932 562 872 388
   2 390 566 106 772 822 477 703 402 730]


16. Random Float Dataset - This is exactly how sample ML datasets are generated

In [23]:
np.random.seed(42)

X = np.random.rand(5,3)

print(X)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


17. Boolean Masking

In [24]:
marks = np.array([35,55,78,92,48])

passed = marks > 50

print(passed)

[False  True  True  True False]


18. Conditional Filtering - Used heavily during data cleaning

In [25]:
marks = np.array([35,55,78,92,48])

print(marks[marks > 50])

[55 78 92]


19. Replace Values

In [26]:
marks = np.array([35,55,78,92,48])

marks[marks < 50] = 50

print(marks)

[50 55 78 92 50]


20. Log Transformation - Very common in ML

In [27]:
salary = np.array([1000,5000,10000])

print(np.log(salary))

[6.90775528 8.51719319 9.21034037]


21. Square Root

In [ ]:
nums = np.array([4,9,16,25])

print(np.sqrt(nums))

[2. 3. 4. 5.] ,


22. Exponential

In [5]:
nums = np.array([1,2,3])

print(np.exp(nums))

[ 2.71828183  7.3890561  20.08553692]


23. Dot Product - Used in Linear Regression and Neural Networks.

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.dot(a,b)

print(result)

32


24. Matrix Multiplication - Extremely important for Deep Learning

In [9]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A @ B)

[[19 22]
 [43 50]]


25. Determinant

In [10]:
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.det(A))

-2.0000000000000004


26. Inverse

In [ ]:
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.inv(A))

27. Mean

In [11]:
data = np.array([10,20,30,40])

print(np.mean(data))

25.0


28. Median

In [12]:
data = np.array([10,20,30,40])
print(np.median(data))

25.0


29. Variance

In [14]:
data = np.array([10,20,30,40])
print(np.var(data))

125.0


30. Standard Deviation

In [15]:
data = np.array([10,20,30,40])
print(np.std(data))

11.180339887498949


31. Missing Values

In [16]:
data = np.array([
    1,
    2,
    np.nan,
    4
])

print(np.isnan(data))

[False False  True False]


32. Replace Missing Values

In [17]:
data = np.array([
    1,
    2,
    np.nan,
    4
])

mean_value = np.nanmean(data)

data[np.isnan(data)] = mean_value

print(data)

[1.         2.         2.33333333 4.        ]


ML Mini Project: Feature Scaling from Scratch

In [22]:
import numpy as np

np.random.seed(42)

X = np.random.randint(
    10,
    100,
    (5,3)
)

print("Original Data")
print(X)

mean = np.mean(X, axis=0)

std = np.std(X, axis=0)

X_scaled = (X - mean) / std

print("\nMean:", mean)


print("\nStd:",std)

print("\nScaled Data:")
print(X_scaled)

Original Data
[[61 24 81]
 [70 30 92]
 [96 84 84]
 [97 33 12]
 [31 62 11]]

Mean: [71.  46.6 56. ]

Std: [24.50306103 22.83506076 36.51301138]

Scaled Data:
[[-0.40811228 -0.98970615  0.68468743]
 [-0.04081123 -0.7269523   0.9859499 ]
 [ 1.02028069  1.6378323   0.76684992]
 [ 1.06109192 -0.59557538 -1.20504988]
 [-1.6324491   0.67440153 -1.23243738]]


ML Mini Project: Outlier Detection

In [24]:
import numpy as np

salary = np.array([
    25000,
    28000,
    30000,
    32000,
    35000,
    400000
])

mean = np.mean(salary)
std = np.std(salary)

z_scores = (salary - mean) / std

outliers = salary[np.abs(z_scores) > 2]

print("Outliers:", outliers)

Outliers: [400000]
