Module 1: Dataset Handling
Module 2: Preprocessing
Module 3: Regression
Module 4: Classification
Module 5: Evaluation Metrics
Module 6: Cross Validation
Module 7: Hyperparameter Tuning
Module 8: Feature Selection
Module 9: Dimensionality Reduction
Module 10: Clustering
Module 11: Pipelines
Module 12: Model Persistence

MASTER DATASET

In [6]:
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    "Age": np.random.randint(20,60,100),
    "Salary": np.random.randint(30000,100000,100),
    "Experience": np.random.randint(1,20,100),
    "Gender": np.random.choice(["Male","Female"],100),
    "Department": np.random.choice(["IT","HR","Finance"],100),
    "Purchased": np.random.choice([0,1],100)
})

print(df)
print(df.shape)

    Age  Salary  Experience  Gender Department  Purchased
0    58   65222          16  Female         IT          1
1    48   93335          16    Male         HR          0
2    34   40965          17  Female         IT          1
3    27   54538           2  Female    Finance          0
4    40   38110           1  Female    Finance          0
..  ...     ...         ...     ...        ...        ...
95   28   77254          18  Female         HR          0
96   27   51918          13    Male         IT          1
97   31   90713           7    Male    Finance          1
98   53   60306           4  Female    Finance          0
99   52   46646          13    Male         HR          0

[100 rows x 6 columns]
(100, 6)


MODULE 1: TRAIN TEST SPLIT

In [10]:
from sklearn.model_selection import train_test_split

X = df[["Age","Salary","Experience"]]

y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(80, 3)
(20, 3)


MODULE 2: PREPROCESSING

SimpleImputer

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

df.loc[0,"Age"] = np.nan #makes age's first value 0, so we will find mean using next step

imputer = SimpleImputer(strategy="mean")

df["Age"] = imputer.fit_transform(
    df[["Age"]]
)

print(df)

         Age  Salary  Experience  Gender Department  Purchased
0   38.59596   65222          16       0         IT          1
1   48.00000   93335          16       1         HR          0
2   34.00000   40965          17       0         IT          1
3   27.00000   54538           2       0    Finance          0
4   40.00000   38110           1       0    Finance          0
..       ...     ...         ...     ...        ...        ...
95  28.00000   77254          18       0         HR          0
96  27.00000   51918          13       1         IT          1
97  31.00000   90713           7       1    Finance          1
98  53.00000   60306           4       0    Finance          0
99  52.00000   46646          13       1         HR          0

[100 rows x 6 columns]


LabelEncoder

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(
    df["Gender"]
)

print(df.head(10))

        Age  Salary  Experience  Gender Department  Purchased
0  38.59596   65222          16       0         IT          1
1  48.00000   93335          16       1         HR          0
2  34.00000   40965          17       0         IT          1
3  27.00000   54538           2       0    Finance          0
4  40.00000   38110           1       0    Finance          0
5  58.00000   57266          16       0         HR          0
6  38.00000   82992          12       0    Finance          0
7  42.00000   36910           5       0         IT          0
8  30.00000   30206           5       1         HR          0
9  30.00000   53419           9       1         IT          0


OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded = encoder.fit_transform(
    df[["Department"]]
)

print(encoded.toarray())


[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1.

StandardScaler

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled = scaler.fit_transform(
    df[["Age","Salary"]]
)

print(scaled[:5])

[[ 6.26866658e-16 -5.70245455e-02]
 [ 8.29658666e-01  1.29089199e+00]
 [-4.05472280e-01 -1.22005984e+00]
 [-1.02303775e+00 -5.69283650e-01]
 [ 1.23869554e-01 -1.35694675e+00]]


MinMaxScaler

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled = scaler.fit_transform(
    df[["Age","Salary"]]
)

print(scaled[:5])

[[0.47681948 0.50779471]
 [0.71794872 0.91548356]
 [0.35897436 0.15602477]
 [0.17948718 0.35285758]
 [0.51282051 0.11462216]]


RobustScaler

Used when outliers exist.

In [16]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

scaled = scaler.fit_transform(
    df[["Salary"]]
)

print(scaled[:5])

[[-0.06315474]
 [ 0.7788985 ]
 [-0.78971133]
 [-0.38316672]
 [-0.87522558]]


ColumnTransformer

Interview favorite.

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer([
    ("num", StandardScaler(),
     ["Age","Salary","Experience"]),
    ("cat", OneHotEncoder(),
     ["Department"])
])

result = preprocessor.fit_transform(df)

print(result.shape)

(100, 6)


MODULE 3: REGRESSION
Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

pred = model.predict(X)

print(pred[:5])

[0.43415833 0.44799655 0.4321612  0.36381626 0.3853578 ]


Regression Metrics

In [ ]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print(mean_absolute_error(y,pred))

print(mean_squared_error(y,pred))

print(r2_score(y,pred))

MODULE 4: CLASSIFICATION

Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

X = df[["Age","Salary","Experience"]]

y = df["Purchased"]

model = LogisticRegression()

model.fit(X,y)

pred = model.predict(X)

print(pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(
    n_neighbors=5
)

model.fit(X,y)

pred = model.predict(X)

print(pred)

[1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1
 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1]


Decision Tree

In [28]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    random_state=42
)

model.fit(X,y)

pred = model.predict(X)

print(pred)

[1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 1 1 0 1
 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1
 0 0 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 0 1 1 0 0]


Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X,y)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

Feature Importance:

In [30]:
print(model.feature_importances_)

[0.36938607 0.37592745 0.25468648]


SVM

In [32]:
from sklearn.svm import SVC

model = SVC()

model.fit(X,y)

pred = model.predict(X)

print(pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


MODULE 5: CLASSIFICATION METRICS
Accuracy

In [33]:
from sklearn.metrics import accuracy_score

print(
    accuracy_score(
        y_test,
        y_pred
    )
)

NameError: name 'y_pred' is not defined

Confusion Matrix


In [34]:
from sklearn.metrics import confusion_matrix

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

NameError: name 'y_pred' is not defined

Precision

In [ ]:
from sklearn.metrics import precision_score

print(
    precision_score(
        y_test,
        y_pred
    )
)

Recall

In [ ]:
from sklearn.metrics import recall_score

print(
    recall_score(
        y_test,
        y_pred
    )
)

F1 Score

In [ ]:
from sklearn.metrics import f1_score

print(
    f1_score(
        y_test,
        y_pred
    )
)

ROC AUC

In [35]:
from sklearn.metrics import roc_auc_score

probs = model.predict_proba(
    X_test
)[:,1]

print(
    roc_auc_score(
        y_test,
        probs
    )
)

AttributeError: This 'SVC' has no attribute 'predict_proba'

MODULE 6: CROSS VALIDATION

KFold

In [37]:
from sklearn.model_selection import KFold

kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

print(kf)

KFold(n_splits=5, random_state=42, shuffle=True)


Cross Validation

In [38]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X,
    y,
    cv=5
)

print(scores)

print(scores.mean())

[0.55 0.6  0.6  0.6  0.6 ]
0.5900000000000001



MODULE 7: HYPERPARAMETER TUNING

GridSearchCV

In [39]:
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators":[50,100,200],
    "max_depth":[2,5,10]
}

grid = GridSearchCV(
    RandomForestClassifier(),
    params,
    cv=5
)

grid.fit(X,y)

print(grid.best_params_)

print(grid.best_score_)

{'max_depth': 2, 'n_estimators': 200}
0.5900000000000001


RandomizedSearchCV

In [40]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    RandomForestClassifier(),
    params,
    cv=5
)

random_search.fit(X,y)

print(random_search.best_params_)

/Users/ra20549220/Desktop/ML/.venv/lib/python3.12/site-packages/sklearn/model_selection/_search.py:326: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


{'n_estimators': 200, 'max_depth': 2}


MODULE 8: FEATURE SELECTION
SelectKBest

In [42]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

selector = SelectKBest(
    score_func=f_classif,
    k=2
)

X_new = selector.fit_transform(
    X,
    y
)

print(X_new)

[[38.5959596 16.       ]
 [48.        16.       ]
 [34.        17.       ]
 [27.         2.       ]
 [40.         1.       ]
 [58.        16.       ]
 [38.        12.       ]
 [42.         5.       ]
 [30.         5.       ]
 [30.         9.       ]
 [43.         9.       ]
 [55.         3.       ]
 [59.        19.       ]
 [43.        16.       ]
 [22.        16.       ]
 [41.         3.       ]
 [21.         1.       ]
 [43.        11.       ]
 [49.        17.       ]
 [57.         8.       ]
 [21.         4.       ]
 [40.         6.       ]
 [52.         8.       ]
 [31.         3.       ]
 [41.        16.       ]
 [44.         3.       ]
 [46.        18.       ]
 [47.        14.       ]
 [35.        18.       ]
 [34.         2.       ]
 [22.         3.       ]
 [56.        16.       ]
 [26.         9.       ]
 [40.         4.       ]
 [28.         1.       ]
 [58.         4.       ]
 [37.         1.       ]
 [23.        14.       ]
 [44.        16.       ]
 [33.         8.       ]


Feature Importance

In [43]:
model = RandomForestClassifier()

model.fit(X,y)

print(
    model.feature_importances_
)

[0.35408183 0.39555315 0.25036502]


MODULE 9: PCA

Interview Favorite.

In [44]:
from sklearn.decomposition import PCA

pca = PCA(
    n_components=2
)

X_pca = pca.fit_transform(X)

print(X_pca)

[[-1.18933998e+03  4.34514340e-01]
 [ 2.69236601e+04  9.48051701e+00]
 [-2.54463400e+04 -3.79628911e+00]
 [-1.18733402e+04 -1.18951900e+01]
 [-2.83013400e+04  1.21368818e+00]
 [-9.14533975e+03  1.98956596e+01]
 [ 1.65806600e+04 -6.27762392e-01]
 [-2.95013400e+04  3.47726964e+00]
 [-3.62053401e+04 -8.41779605e+00]
 [-1.29923401e+04 -8.44475649e+00]
 [ 1.42246601e+04  4.20080979e+00]
 [ 1.36036602e+04  1.58045869e+01]
 [ 1.78566603e+04  2.07577019e+01]
 [-1.82703399e+04  5.03581611e+00]
 [ 1.96326598e+04 -1.63794097e+01]
 [ 3.08026600e+04  1.62513265e+00]
 [-2.58434023e+03 -1.80585180e+01]
 [ 1.94086601e+04  4.26481892e+00]
 [ 2.62116601e+04  1.05503812e+01]
 [-1.41123398e+04  1.84513695e+01]
 [ 7.17365978e+03 -1.79864178e+01]
 [ 2.76326600e+04  8.55217080e-01]
 [ 6.14566016e+03  1.32169711e+01]
 [ 1.26686599e+04 -8.13603484e+00]
 [-3.37183400e+04  3.22620885e+00]
 [ 3.27516600e+04  4.59560525e+00]
 [-1.04723399e+04  8.06227441e+00]
 [ 1.25136601e+04  8.52982632e+00]
 [ 6.52965998e+03 -3

Explained Variance

In [45]:
print(
    pca.explained_variance_ratio_
)

[9.99999621e-01 2.96064133e-07]


MODULE 10: CLUSTERING

No target variable.

KMeans

In [46]:
from sklearn.cluster import KMeans

model = KMeans(
    n_clusters=3,
    random_state=42
)

clusters = model.fit_predict(X)

print(clusters)

[2 0 1 1 1 1 0 1 1 1 2 2 0 1 0 0 2 0 0 1 2 0 2 2 1 0 1 2 2 1 1 1 1 1 2 1 2
 0 0 1 0 1 0 1 1 1 1 0 2 0 0 0 2 2 2 0 0 0 1 0 1 1 2 1 0 2 2 1 0 0 1 1 2 0
 0 0 2 1 1 2 0 1 2 1 0 2 1 1 0 1 1 2 1 1 2 2 1 0 2 1]


DBSCAN

In [47]:
from sklearn.cluster import DBSCAN

model = DBSCAN(
    eps=0.5,
    min_samples=5
)

clusters = model.fit_predict(X)

print(clusters)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1]


Hierarchical

In [48]:
from sklearn.cluster import AgglomerativeClustering

model = AgglomerativeClustering(
    n_clusters=3
)

clusters = model.fit_predict(X)

print(clusters)

[0 1 2 0 2 0 1 2 2 0 1 1 1 2 1 1 0 1 1 0 0 1 0 1 2 1 0 1 0 0 2 0 2 0 0 0 0
 1 1 2 1 2 1 0 2 2 2 1 0 1 1 1 1 0 0 1 1 1 0 1 0 2 0 2 1 0 1 0 1 1 2 0 0 1
 1 1 0 0 0 0 1 2 1 2 1 0 2 2 1 2 2 0 2 2 0 0 0 1 0 2]


MODULE 11: PIPELINES

Very Important ML Engineer Topic.

In [50]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

pipeline.fit(
    X_train,
    y_train
)

pred = pipeline.predict(
    X_test
)

print(pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


MODULE 12: MODEL SAVING
Save Model

In [ ]:
import joblib

joblib.dump(
    model,
    "model.pkl"
)

Load Model

In [ ]:
model = joblib.load(
    "model.pkl"
)